---
genPolicy: "None"
openAPISpec: "http://18.144.38.115:8090/v2/api-docs"
generators:
- type: "no_params"
  assertions:
  - "@StatusCode == 200"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "sla"
  assertions:
  - "@StatusCode == 200 AND @ResponseTime < 500"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: "Get:/api/v1/user-signup/**"
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid_empty"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "auth_invalid_sql"
  assertions:
  - "@StatusCode == 401 OR @StatusCode == 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: null
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: ""
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "rbac"
  assertions:
  - "--Allowed Assertions"
  - "@StatusCode == 401 OR @StatusCode == 403"
  - "--Disallowed Assertions"
  - "@StatusCode != 401 AND @StatusCode != 403"
  severity: null
  database: null
  inactive: true
  matches:
  - name: "ROLE_ADMIN,ROLE_PM,ROLE_USER"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: "Get:/api/v1/orgs/:Allowed[ROLE_ADMIN]\nPost:/api/v1/accounts/:Allowed[ROLE_ADMIN,ROLE_PM]"
    queryParams: null
    bodyProperties: null
- type: "DDOS"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches:
  - name: "pageSize, page_size, maxResults, max_results"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime < 7000 OR @ResponseTime > 10000"
  - "@StatusCode != 404"
  severity: null
  database:
    name: "MySQL"
    version: "5.7"
  inactive: true
  matches: []
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "null_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "negative_number"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  severity: null
  database: null
  inactive: true
  matches: null
- type: "create"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  severity: null
  database: null
  inactive: true
  matches: null
